name: Build & Sign APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew assembleDebug assembleRelease --parallel --build-cache --daemon

      - name: Sign APKs
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore app/release.keystore \
            -storepass junixald \
            -keypass junixald \
            app/build/outputs/apk/debug/app-debug.apk githubrelease
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
            -keystore app/release.keystore \
            -storepass junixald \
            -keypass junixald \
            app/build/outputs/apk/release/app-release-unsigned.apk githubrelease
          # Align release APK
          $ANDROID_HOME/build-tools/33.0.2/zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release.apk

      - name: Prepare release folder
        run: |
          mkdir release
          cp app/build/outputs/apk/debug/app-debug.apk release/
          cp app/build/outputs/apk/release/app-release.apk release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
